<?php

/**
 * BaseCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $address
 * @property string $phone
 * @property string $logo
 * @property Doctrine_Collection $Company
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method string              getEmail()   Returns the current record's "email" value
 * @method string              getAddress() Returns the current record's "address" value
 * @method string              getPhone()   Returns the current record's "phone" value
 * @method string              getLogo()    Returns the current record's "logo" value
 * @method Doctrine_Collection getCompany() Returns the current record's "Company" collection
 * @method Company             setId()      Sets the current record's "id" value
 * @method Company             setName()    Sets the current record's "name" value
 * @method Company             setEmail()   Sets the current record's "email" value
 * @method Company             setAddress() Sets the current record's "address" value
 * @method Company             setPhone()   Sets the current record's "phone" value
 * @method Company             setLogo()    Sets the current record's "logo" value
 * @method Company             setCompany() Sets the current record's "Company" collection
 * 
 * @package    sf_icox
 * @subpackage model
 * @author     pinika
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompany extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('address', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('phone', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('logo', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AppUser as Company', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}