<?php

/**
 * BaseBedroom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Bedroom
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getBedroom() Returns the current record's "Bedroom" collection
 * @method Bedroom             setId()      Sets the current record's "id" value
 * @method Bedroom             setName()    Sets the current record's "name" value
 * @method Bedroom             setBedroom() Sets the current record's "Bedroom" collection
 * 
 * @package    sf_icox
 * @subpackage model
 * @author     pinika
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBedroom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bedroom');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RealProperty as Bedroom', array(
             'local' => 'id',
             'foreign' => 'bedroom_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}