<?php

/**
 * BasePropertyType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $PropertyType
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getPropertyType() Returns the current record's "PropertyType" collection
 * @method PropertyType        setId()           Sets the current record's "id" value
 * @method PropertyType        setName()         Sets the current record's "name" value
 * @method PropertyType        setPropertyType() Sets the current record's "PropertyType" collection
 * 
 * @package    sf_icox
 * @subpackage model
 * @author     pinika
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePropertyType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('property_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RealProperty as PropertyType', array(
             'local' => 'id',
             'foreign' => 'property_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}