<?php

/**
 * BaseEmailShare
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $email_friend
 * @property text $comment
 * @property text $url
 * 
 * @method integer    getId()           Returns the current record's "id" value
 * @method string     getName()         Returns the current record's "name" value
 * @method string     getEmail()        Returns the current record's "email" value
 * @method string     getEmailFriend()  Returns the current record's "email_friend" value
 * @method text       getComment()      Returns the current record's "comment" value
 * @method text       getUrl()          Returns the current record's "url" value
 * @method EmailShare setId()           Sets the current record's "id" value
 * @method EmailShare setName()         Sets the current record's "name" value
 * @method EmailShare setEmail()        Sets the current record's "email" value
 * @method EmailShare setEmailFriend()  Sets the current record's "email_friend" value
 * @method EmailShare setComment()      Sets the current record's "comment" value
 * @method EmailShare setUrl()          Sets the current record's "url" value
 * 
 * @package    sf_icox
 * @subpackage model
 * @author     pinika
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmailShare extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('email_share');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('email', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('email_friend', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('comment', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('url', 'text', null, array(
             'type' => 'text',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}