default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, admin.css, /js/alerts/jquery.alerts.css]

  javascripts:    [/js/jquery.min.js, /js/functions.js, /js/alerts/jquery.alerts.js, /js/country.js]

  has_layout:     true
  layout:         layout