<?php

/**
 * BaseOperation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Operation
 * 
 * @method integer             getId()                      Returns the current record's "id" value
 * @method string              getName()                    Returns the current record's "name" value
 * @method Doctrine_Collection getOperationRealProperties() Returns the current record's "OperationRealProperties" collection
 * @method Doctrine_Collection getOperation()               Returns the current record's "Operation" collection
 * @method Operation           setId()                      Sets the current record's "id" value
 * @method Operation           setName()                    Sets the current record's "name" value
 * @method Operation           setOperationRealProperties() Sets the current record's "OperationRealProperties" collection
 * @method Operation           setOperation()               Sets the current record's "Operation" collectionRealProperties
 * @property Doctrine_Collection $Operation
 * 
 * @method integer             getId()                      Returns the current record's "id" value
 * @method string              getName()                    Returns the current record's "name" value
 * @method Doctrine_Collection getOperationRealProperties() Returns the current record's "OperationRealProperties" collection
 * @method Doctrine_Collection getOperation()               Returns the current record's "Operation" collection
 * @method Operation           setId()                      Sets the current record's "id" value
 * @method Operation           setName()                    Sets the current record's "name" value
 * @method Operation           setOperationRealProperties() Sets the current record's "OperationRealProperties" collection
 * @method Operation           setOperation()               Sets the current record's "Operation" collection
 * 
 * @package    sf_icox
 * @subpackage model
 * @author     pinika
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOperation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('operation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OperationRealProperty as OperationRealProperties', array(
             'local' => 'id',
             'foreign' => 'operation_id'));

        $this->hasMany('SearchProfile as Operation', array(
             'local' => 'id',
             'foreign' => 'operation_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}