<?php

/**
 * BaseGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $former_name
 * @property string $internal_name
 * @property boolean $outstanding
 * @property integer $real_property_id
 * @property RealProperty $RealProperty
 * 
 * @method integer      getId()               Returns the current record's "id" value
 * @method string       getFormerName()       Returns the current record's "former_name" value
 * @method string       getInternalName()     Returns the current record's "internal_name" value
 * @method boolean      getOutstanding()      Returns the current record's "outstanding" value
 * @method integer      getRealPropertyId()   Returns the current record's "real_property_id" value
 * @method RealProperty getRealProperty()     Returns the current record's "RealProperty" value
 * @method Gallery      setId()               Sets the current record's "id" value
 * @method Gallery      setFormerName()       Sets the current record's "former_name" value
 * @method Gallery      setInternalName()     Sets the current record's "internal_name" value
 * @method Gallery      setOutstanding()      Sets the current record's "outstanding" value
 * @method Gallery      setRealPropertyId()   Sets the current record's "real_property_id" value
 * @method Gallery      setRealProperty()     Sets the current record's "RealProperty" value
 * 
 * @package    sf_icox
 * @subpackage model
 * @author     pinika
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gallery');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('former_name', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('internal_name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('outstanding', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('real_property_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RealProperty', array(
             'local' => 'real_property_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}