# loging
loging:
  url: loging
  param: { module: user, action: loging }
# logout
logout:
  url: logout
  param: { module: user, action: logout }
# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# generic rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*