default:
  http_metas:
    content-type: text/html

  metas:
    title:        Inmobiliaria Lamarca
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [styles.css, /js/jqtransformplugin/jqtransform.css]

  javascripts:    [jquery.min.js, /js/jqtransformplugin/jquery.jqtransform.js]

  has_layout:     true
  layout:         layout