prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=ilamarca_com'
      username: lmarca
      password: control007

stage:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=ilamarca_com'
      username: lmarca
      password: control007

dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=ilamarca_com'
      username: lmarca
      password: control007