all:
  project_reference_name: ilamarca
  no_replay_email_account: noreply@emailbase.com.ar
   
  outgoing_smtp_server: smtp.gmail.com
  outgoing_smtp_port: 465
  outgoing_smtp_account: icox.automatic.service@gmail.com
  outgoing_smtp_password: la-virginia