# detail property
#detail_property:
#  url: /detail-property/:id/:name.html
#  param: {module: property, action: detailProperty}


# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# generic rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*