default:
  http_metas:
    content-type: text/html

  metas:
    title:        Inmobiliaria Lamarca
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [styles.css]

  javascripts:    [jquery.min.js, jquery.tools.min.js, /admin/js/numvalidate.js, search.js]

  has_layout:     true
  layout:         layout