<?php

/**
 * Country
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_icox
 * @subpackage model
 * @author     pinika
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Country extends BaseCountry
{
  /**
   * get country for select
   * @return array()
   */
  public static function getCountryForSelect()
  {
    $array = array();
    $countrys = CountryTable::getInstance()->findAll();

    foreach($countrys AS $country)
    {
      $array[$country->getId()] = $country->getName();
    }

    return $array;
  }

  /**
   * get culture for select
   * @return array
   */
  public static function getCultureForSelect()
  {
    $array = array();
    $countrys = CountryTable::getInstance()->findAll();

    foreach($countrys AS $country)
    {
      $array[$country->getIso()] = $country->getName();
    }

    return $array;
  }
}
