<?php

/**
 * OperationRealProperty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_icox
 * @subpackage model
 * @author     pinika
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OperationRealProperty extends BaseOperationRealProperty
{
    /**
     * get Data Operations By Property Id
     * @param int $property_id
     * @return array()
     */
    public static function getDataOperationsByPropertyId($property_id)
    {
        $array_data = array('operations'=>array(), 'currencies'=>array(), 'prices'=>array());

        $operations = OperationRealPropertyTable::getInstance()->getOperationsByPropertyId($property_id);

        foreach ( $operations as $value) 
        {
            $array_data['operations'][] = $value->getOperationId();
            $array_data['currencies'][$value->getOperationId()]['id'] = $value->getCurrencyId();
            $array_data['prices'][$value->getOperationId()]['number'] = $value->getPrice();
        }
        
        return $array_data;

    }
}
