<?php

/**
 * Operation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_icox
 * @subpackage model
 * @author     pinika
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Operation extends BaseOperation
{
	/**
	 * Get prices
	 *
	 * @param integer $property
	 * @param string $culture
	 * @param boolean $venta_o_alquiler
	 * 
	 * @return decimal
	 */
  public static function getPrices($property, $culture, $venta_o_alquiler = false)
  {
    $operation = OperationRealPropertyTable::getInstance()->getOperationsByPropertyIdAndCulture($property, $culture);

    if (!$operation) {
      $operation = OperationRealPropertyTable::getInstance()->getOperationsByPropertyIdAndCulture($property, 'en');
    }
    if ($venta_o_alquiler) {
    	return $operation->getOperationId();
    } else {
    	return $operation->getCurrency()->getSymbol().' '. $operation->getPrice();
    }
  }

} // end class