prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.0.0.1;port=3310;dbname=ilamarca_com'
      username: root
      password: root

stage:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.0.0.1;port=3310;dbname=ilamarca_com'
      username: root
      password: root

dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.0.0.1;port=3310;dbname=ilamarca_com'
      username: root
      password: root